log:
  level: "info"  # possible values: "debug", "info", "warn", "error"
  format: "text" # possible values: "text", "json"
# path to the reports output directory
output: "reports"
kubernetesClient:
  # inCluster, when set to true, attempts to authenticate with the API
  # server using a service account token.
  #
  # Either `inCluster` must be set to true or the path to a kubeconfig
  # file must be provided below.
  inCluster: false
  # Kubeconfig is the path to the `kubeconfig` file. This is useful when
  # running the application outside the cluster.
  #
  # Either `inCluster` must be set to true or the path to a kubeconfig
  # file must be provided here.
  kubeconfig: ""
rabbitmq:
  # enable rabbitmq metrics and stats in the reports.
  enable: false
  # kubernetes headless fqdn address pointing to rabbitmq nodes. On a DNS
  # lookup, this address must resolve to rabbitmq node ips.
  #
  # For example: rabbitmq-nodes.default.svc.cluster.local
  headlessSvcAddr: ""
  management:
    # rabbitmq management url.
    #
    # For example: http://rabbitmq.default.svc.cluster.local:15672
    url: ""
    # basic auth username for the management api.
    username: ""
    # basic auth password for the management api.
    password: ""
