log:
  level: "info"  # possible values: "debug", "info", "warn", "error"
  format: "text" # possible values: "text", "json"
# path to the reports output directory
output: "reports"
# sets the period after which the web server must be forcefully
# terminated. A value of 0 implies no forceful termination.
terminationGracePeriod: 10s
kubernetesClient:
  # inCluster, when set to true, attempts to authenticate with the API
  # server using a service account token.
  #
  # Either `inCluster` must be set to true or the path to a kubeconfig
  # file must be provided below.
  inCluster: false
  # Kubeconfig is the path to the `kubeconfig` file. This is useful when
  # running the application outside the cluster.
  #
  # Either `inCluster` must be set to true or the path to a kubeconfig
  # file must be provided here.
  kubeconfig: ""
rabbitmq:
  # enable rabbitmq metrics and stats in the reports.
  enable: false
  # kubernetes headless fqdn address pointing to rabbitmq nodes. On a DNS
  # lookup, this address must resolve to rabbitmq node ips.
  #
  # For example: rabbitmq-nodes.default.svc.cluster.local
  headlessSvcAddr: ""
  management:
    # rabbitmq management url.
    #
    # For example: http://rabbitmq.default.svc.cluster.local:15672
    url: ""
    # basic auth username for the management api.
    username: ""
    # basic auth password for the management api.
    password: ""
longRunningJobs:
  # enable long-running jobs reporting
  enable: false
  # namespace in which the long-running jobs will be reported. Leave blank for
  # all namespaces.
  namespace: ""
  # jobs older than this value will be reported.
  #
  # Eg: 12h, 30m, 5h30m15s
  olderThan: 24h
  # include long-running suspended jobs in reports
  includeSuspended: false
imageTag:
  # enable image tag report
  enable: false
  # kubernetes namespace that the image tag reporter will be limited to.
  namespace: ""
deploymentAndStatefulsetStatus:
  # enable deployment and statefulset status (DaSS) reporter
  enable: false
  # kubernetes namespace that the deployment and statefulset status (DaSS)
  # reporter will be limited to. Leave blank for all namespaces.
  namespace: ""
