---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvc.name" . }}
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.persistentVolumeClaim.spec | nindent 2 }}
