---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccount.name" . }}
  namespace: {{ include "namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clusterRole.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - pods/status
      - events
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - statefulsets
      - events
    verbs:
      - get
      - list
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - events
    verbs:
      - get
      - list
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clusterRoleBinding.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clusterRole.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccount.name" . }}
    namespace: {{ include "namespace" . }}
