{{ if .Values.secretConfig.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.name" . }}
  namespace: {{ include "namespace" . }}
type: Opaque
stringData:
  secret.yaml: |-
    {{- toYaml .Values.secretConfig.config | nindent 4 }}
{{- end }}
