---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.name" . }}
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deployment.selectorLabels" . | nindent 4 }}
